### ISSUE TITLE
Fails to parse `nickname` from YAML

### ISSUE THREAD

**Issue by phrohdoh** [8573/irc-bot.rs#7]
Bug encountered on 405ed0cbc4525bed35cf6382dba19482605db6d0.

This yaml always yields `Error(Config("nickname", "is not specified") ...)`:

```yaml
nickname: testbot
username: testbot
realname: testbot
channels: ["#botters-test"]
servers:
  - host: irc.freenode.net
    port: 6667
admins:
  - nick: Phrohdoh
    user: Phrohdoh
```

**Comment by 8573** [comment]
I've failed to reproduce this issue, but in trying to do so, I have
fixed another issue that was (for me) preventing the bot from starting
completely:

<https://github.com/8573/irc-bot.rs/commit/4681c1aa341c5b2a323e3360cd5191d7acf820a4>

Do you still get `Error(Config("nickname", "is not specified"), ...)`
on latest `wip/yak-irc/1`?

**Comment by phrohdoh** [comment]
I still get the nickname config error on 4681c1a.

**Comment by 8573** [comment]
I deleted `Cargo.lock`, ran `cargo clean`, rebuilt everything, pasted
in your configuration, and still failed to reproduce your issue. :/

Maybe something's wrong with your repository? Also, are you sure there
isn't a typo in your configuration?

**Comment by 8573** [comment]
Oh! You're not running the default bot (with `cargo run`), are you?

**Comment by 8573** [comment]
Oh! You're running something other than the default bot (run with
`cargo run`), aren't you? (As in #6.)

**Comment by phrohdoh** [comment]
This is exactly what I am running (via `cargo run`):

```toml
[package]
authors = ["Taryn Hill <taryn@phrohdoh.com>"]
name = "ircb"
version = "0.1.0"

[dependencies]
irc-bot = { git = "https://github.com/8573/irc-bot.rs.git", branch = "wip/yak-irc/1" }
```

```rust
extern crate irc_bot as irc;

fn main() {
    irc::run("config.yaml", |e| {
        println!("{:?}", e);
        irc::core::ErrorReaction::Proceed
    }, &[irc::modules::default(), irc::modules::test()]);
}
```

```yaml
# config.yaml
nickname: ircb
username: ircb
realname: ircb
channels: ["#orcaware"]
servers:
  - host: irc.freenode.org
    port: 6667
admins:
  - nick: Phrohdoh
    user: Phrohdoh
```
